
# Vectorization

In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [4]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print("Vectorized version: " + str(1000 * (toc - tic)))

c = 0
tic = time.time()
for i in range(len(a)):
    c += a[i] * b[i]
toc = time.time()

print("Loop version: " + str(1000 * (toc - tic)))

Vectorized version: 0.8749961853027344
Loop version: 434.6497058868408


# Broadcasting

In [6]:
import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0], 
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [10]:
cal = A.sum(axis = 0)
print(cal)

[  59.   239.   155.4   76.9]


In [12]:
percentage = 100 * A / cal.reshape(1, 4)
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [13]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [16]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(a)
print(b)
print(c)

[[ 1.44130065  0.97120339 -0.7914226 ]
 [-1.13040054  0.22732151 -0.13417963]
 [ 0.1548803  -0.01763305 -0.41144326]]
[[-0.46802692]
 [-0.91286591]
 [ 0.50309404]]
[[-0.67456751 -0.45454933  0.37040708]
 [ 1.03190412 -0.20751406  0.12248801]
 [ 0.07791936 -0.00887108 -0.20699465]]


In [21]:
a = np.array([[1, 2], [1, 2]])
b = np.array([[2], [3]])
print(a.shape, b.shape)
for i in range(2):
    for j in range(2):
        c[i][j] = a[i][j] + b[j]
print(c)
c = a + b.T
print(c)

(2, 2) (2, 1)
[[3 5]
 [3 5]]
[[3 5]
 [3 5]]


In [22]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(c.shape)

(2, 3)


In [26]:
a = np.random.randn(3,2,2)
print(a)
c = a.reshape(2*2*3, 1)
print(c)

[[[-1.69493952  0.70665654]
  [-0.98297796  0.7438456 ]]

 [[ 0.99077082 -0.63165058]
  [ 0.99843577 -0.92948516]]

 [[ 1.47381452  1.17191751]
  [-1.52330418 -1.41111   ]]]
[[-1.69493952]
 [ 0.70665654]
 [-0.98297796]
 [ 0.7438456 ]
 [ 0.99077082]
 [-0.63165058]
 [ 0.99843577]
 [-0.92948516]
 [ 1.47381452]
 [ 1.17191751]
 [-1.52330418]
 [-1.41111   ]]


In [27]:
print(a)


[[[-1.69493952  0.70665654]
  [-0.98297796  0.7438456 ]]

 [[ 0.99077082 -0.63165058]
  [ 0.99843577 -0.92948516]]

 [[ 1.47381452  1.17191751]
  [-1.52330418 -1.41111   ]]]


In [30]:
a = [0.1, 0.500987, 0.35]
print(np.round(a))

[ 0.  1.  0.]


Each node has two computations: 
	1. z<sup>[1]</sup><sub>1</sub> = w<sup>[1]T</sup><sub>1</sub>x + b<sup>[1]</sup><sub>1</sub>
	2. a<sup>[1]</sup><sub>1</sub> = $\sigma(z^{[1]}\sub{1})$

In [36]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
print(B.shape)

(4, 1)


$$ \hat_{y} = \sigma(Z^{[1]})$$